FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    g++ \
    qtbase5-dev \
    qttools5-dev \
    qttools5-dev-tools \
    qt5-qmake \
    qtcreator \
    libqt5svg5-dev \
    libgl1-mesa-dev \
    libx11-dev \
    x11-apps \
    libxcb1 \
    libxcb-xinerama0 \
    libxcb-xinput0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-render-util0 \
    libxcb-xfixes0 \
    libxkbcommon-x11-0 \
    libxrender1 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD [ "bash" ]
