#include "xmlService.h"
#include <QFile>
#include <QDomDocument>
#include <QDebug>
#include "../logic/film.h"
#include "../logic/serieTv.h"
#include "../logic/anime.h"
#include "../logic/libro.h"
#include "../logic/manga.h"
#include "../logic/cd.h"

XmlService::XmlService(QObject *parent) : QObject(parent) {}

bool XmlService::loadFromFile(const QString &filePath) {
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly)) {
        qWarning() << "Impossibile aprire il file XML:" << filePath;
        return false;
    }
    
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly)) {
        qWarning() << "Impossibile aprire il file XML:" << filePath;
        return false;
    }
    
    QDomDocument doc;
    if (!doc.setContent(&file)) {
        qWarning() << "Formato XML non valido";
        file.close();
        return false;
    }
    
    QDomElement root = doc.documentElement();
    if (root.tagName() != "biblioteca") {
        qWarning() << "Radice XML non valida";
        return false;
    }
    
    QDomNodeList mediaList = root.elementsByTagName("media");
    for (int i = 0; i < mediaList.size(); ++i) {
        QDomElement mediaElement = mediaList.at(i).toElement();
        QDomNodeList mediaList = root.elementsByTagName("media");
        for (int i = 0; i < mediaList.size(); ++i) {
            QDomElement mediaElement = mediaList.at(i).toElement();
            QDomNodeList mediaList = root.elementsByTagName("media");
            for (int i = 0; i < mediaList.size(); ++i) {
                QDomElement mediaElement = mediaList.at(i).toElement();
                QDomNodeList mediaList = root.elementsByTagName("media");
                for (int i = 0; i < mediaList.size(); ++i) {
                    QDomElement mediaElement = mediaList.at(i).toElement();
                    QDomNodeList mediaList = root.elementsByTagName("media");
                    for (int i = 0; i < mediaList.size(); ++i) {
                        QDomElement mediaElement = mediaList.at(i).toElement();
                        QDomNodeList mediaList = root.elementsByTagName("media");
                        for (int i = 0; i < mediaList.size(); ++i) {
                            QDomElement mediaElement = mediaList.at(i).toElement();
                            QDomNodeList mediaList = root.elementsByTagName("media");
                            for (int i = 0; i < mediaList.size(); ++i) {
                                QDomElement mediaElement = mediaList.at(i).toElement();
                                QDomNodeList mediaList = root.elementsByTagName("media");
                                for (int i = 0; i < mediaList.size(); ++i) {
                                    QDomElement mediaElement = mediaList.at(i).toElement();
                                    QDomNodeList mediaList = root.elementsByTagName("media");
                                    for (int i = 0; i < mediaList.size(); ++i) {
                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                        QDomNodeList mediaList = root.elementsByTagName("media");
                                        for (int i = 0; i < mediaList.size(); ++i) {
                                            QDomElement mediaElement = mediaList.at(i).toElement();
                                            QDomNodeList mediaList = root.elementsByTagName("media");
                                            for (int i = 0; i < mediaList.size(); ++i) {
                                                QDomElement mediaElement = mediaList.at(i).toElement();
                                                QDomNodeList mediaList = root.elementsByTagName("media");
                                                for (int i = 0; i < mediaList.size(); ++i) {
                                                    QDomElement mediaElement = mediaList.at(i).toElement();
                                                    QDomNodeList mediaList = root.elementsByTagName("media");
                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                        QDomNodeList mediaList = root.elementsByTagName("media");
                                                        for (int i = 0; i < mediaList.size(); ++i) {
                                                            QDomElement mediaElement = mediaList.at(i).toElement();
                                                            QDomNodeList mediaList = root.elementsByTagName("media");
                                                            for (int i = 0; i < mediaList.size(); ++i) {
                                                                QDomElement mediaElement = mediaList.at(i).toElement();
                                                                QDomNodeList mediaList = root.elementsByTagName("media");
                                                                for (int i = 0; i < mediaList.size(); ++i) {
                                                                    QDomElement mediaElement = mediaList.at(i).toElement();
                                                                    QDomNodeList mediaList = root.elementsByTagName("media");
                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                        QDomNodeList mediaList = root.elementsByTagName("media");
                                                                        for (int i = 0; i < mediaList.size(); ++i) {
                                                                            QDomElement mediaElement = mediaList.at(i).toElement();
                                                                            QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                            for (int i = 0; i < mediaList.size(); ++i) {
                                                                                QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                QDomNodeList mediaList = root.elementsByTagName("media");
                                                                                for (int i = 0; i < mediaList.size(); ++i) {
                                                                                    QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                    QDomNodeList mediaList = root.elementsByTagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsByTagName("media");
                                                                                        for (int i = 0; i < mediaList.size(); ++i) {
                                                                                            QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                            QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsByTagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsByTagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsByTagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).toElement();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList mediaList = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < mediaList.size(); ++i) {
                                                                                        QDomElement mediaElement = mediaList.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elementsBy_tagName("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i) {
                                                                                        QDomElement media_element = media_list.at(i).to_element();
                                                                                        QDomNodeList media_list = root.elements_by_tag_name("media");
                                                                                    for (int i = 0; i < media_list.size(); ++i)
